# Generated by Django 6.0.4 on 2026-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
