# Generated by Django 6.0.4 on 2026-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
